version: '3.9'
services:
  react:
    build:
      args:
        - NODE_VER=20.8.0
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./react-vite-ts-todo:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - 5173:5173

volumes:
  node_modules: